#!/bin/bash
# 🚀 CLAWDESK macOS Build Script (FIXED V2)

echo "🦾 CLAWDESK REAL - Build macOS (Versión Corregida)"
echo "=================================================="

echo "✅ Node.js: $(node --version)"
echo "✅ npm: $(npm --version)"

echo ""
echo "🧹 Limpiando builds anteriores..."
rm -rf dist build out

echo ""
echo "📦 Instalando dependencias CORREGIDAS..."

# Usar versiones específicas que SÍ existen
npm install robotjs@0.6.0
npm install screenshot-desktop@1.15.0
npm install opencv4nodejs@5.6.0
npm install tesseract.js@5.1.0
npm install axios@1.6.0

echo ""
echo "🔧 Actualizando package.json con versiones correctas..."
cat > package-fixed.json << 'EOF'
{
  "name": "clawdesk",
  "version": "1.0.0",
  "description": "CLAWDESK REAL - Agente Autónomo para Control de PC",
  "main": "main-real-complete.js",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "electron": "electron .",
    "electron:dev": "concurrently \"npm run dev\" \"wait-on http://localhost:5173 && electron .\"",
    "dist": "electron-builder",
    "dist:mac": "electron-builder --mac",
    "dist:win": "electron-builder --win",
    "dist:linux": "electron-builder --linux"
  },
  "dependencies": {
    "axios": "^1.6.0",
    "opencv4nodejs": "^5.6.0",
    "robotjs": "^0.6.0",
    "screenshot-desktop": "^1.15.0",
    "tesseract.js": "^5.1.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@vitejs/plugin-react": "^4.0.0",
    "autoprefixer": "^10.0.0",
    "concurrently": "^8.0.0",
    "electron": "^28.0.0",
    "electron-builder": "^24.0.0",
    "postcss": "^8.0.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "tailwindcss": "^3.0.0",
    "typescript": "^5.0.0",
    "vite": "^5.0.0",
    "wait-on": "^7.0.0"
  },
  "build": {
    "appId": "com.clawdesk.real",
    "productName": "CLAWDESK REAL",
    "directories": {
      "output": "dist"
    },
    "files": [
      "dist/**/*",
      "src/**/*",
      "main-real-complete.js",
      "preload-real.js",
      "package.json"
    ],
    "mac": {
      "category": "public.app-category.productivity",
      "target": "dmg",
      "icon": "build/icon.icns"
    },
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "target": "nsis",
      "icon": "build/icon.ico"
    },
    "linux": {
      "target": "AppImage",
      "icon": "build/icon.png"
    }
  }
}
EOF

# Reemplazar package.json
mv package-fixed.json package.json

echo ""
echo "🏗️ Construyendo frontend..."
npm run build

echo ""
echo "🖼️ Generando iconos..."
mkdir -p build

# Crear icono placeholder si no existe
if [ ! -f "build/icon.png" ]; then
  echo "📸 Creando icono placeholder..."
  cat > build/icon.png.base64 << 'EOF'
iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA
AXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGSSURBVHgB
7dixDYAwEATBH8n+twYFpQvQ4Y0z4MxMAAAAAADwqXvvAQAAAAAA4F8BAAAAAACgFAAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
EgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAA
AACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoB
AAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAA
ACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAA
AAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACgEgAAAAAAACoBAAAAAACg
